// VS Code theme palettes for the screenshot harness.
//
// A webview only ever sees its theme as `--vscode-*` custom properties plus a
// `vscode-dark` / `vscode-light` / `vscode-high-contrast` body class. These are
// the values VS Code injects for its three default themes, restricted to the
// names media/*.css and media/*.js actually read. Anything missing here falls
// back to the stylesheet's own fallback — which is exactly what a theme that
// omits a colour does in the real editor.

const FONT = {
  "--vscode-font-family": '-apple-system, BlinkMacSystemFont, "Segoe WPC", "Segoe UI", system-ui, sans-serif',
  "--vscode-font-size": "13px",
  "--vscode-font-weight": "normal",
  "--vscode-editor-font-family": 'Consolas, "Courier New", monospace',
  "--vscode-editor-font-size": "14px",
};

const DARK_MODERN = {
  ...FONT,
  "--vscode-foreground": "#cccccc",
  "--vscode-descriptionForeground": "#9d9d9d",
  "--vscode-disabledForeground": "rgba(204, 204, 204, 0.5)",
  "--vscode-errorForeground": "#f85149",
  "--vscode-focusBorder": "#0078d4",
  "--vscode-contrastBorder": "",
  "--vscode-widget-border": "#313131",
  "--vscode-widget-shadow": "rgba(0, 0, 0, 0.36)",
  "--vscode-sideBar-background": "#181818",
  "--vscode-editor-background": "#1f1f1f",
  "--vscode-editor-foreground": "#cccccc",
  "--vscode-editor-selectionBackground": "#264f78",
  "--vscode-editorLineNumber-foreground": "#6e7681",
  "--vscode-editorWidget-background": "#202020",
  "--vscode-editorWidget-border": "#454545",
  "--vscode-editorWarning-foreground": "#cca700",
  "--vscode-editorGroupHeader-tabsBackground": "#181818",
  "--vscode-tab-activeBackground": "#1f1f1f",
  "--vscode-panel-border": "#2b2b2b",
  "--vscode-toolbar-hoverBackground": "rgba(90, 93, 94, 0.31)",
  "--vscode-list-hoverBackground": "#2a2d2e",
  "--vscode-list-activeSelectionBackground": "#04395e",
  "--vscode-list-activeSelectionForeground": "#ffffff",
  "--vscode-textLink-foreground": "#4daafc",
  "--vscode-textLink-activeForeground": "#4daafc",
  "--vscode-textBlockQuote-background": "#2b2b2b",
  "--vscode-textBlockQuote-border": "#616161",
  "--vscode-textCodeBlock-background": "#2b2b2b",
  "--vscode-textPreformat-foreground": "#d0d0d0",
  "--vscode-button-background": "#0078d4",
  "--vscode-button-foreground": "#ffffff",
  "--vscode-button-hoverBackground": "#026ec1",
  "--vscode-button-border": "rgba(255, 255, 255, 0.07)",
  "--vscode-button-secondaryBackground": "#313131",
  "--vscode-button-secondaryForeground": "#cccccc",
  "--vscode-button-secondaryHoverBackground": "#3c3c3c",
  "--vscode-input-background": "#313131",
  "--vscode-input-border": "#3c3c3c",
  "--vscode-input-foreground": "#cccccc",
  "--vscode-input-placeholderForeground": "#989898",
  "--vscode-inputValidation-errorBackground": "#5a1d1d",
  "--vscode-inputValidation-errorBorder": "#be1100",
  "--vscode-inputValidation-warningBackground": "#352a05",
  "--vscode-inputValidation-warningBorder": "#b89500",
  "--vscode-inputValidation-infoBackground": "#063b49",
  "--vscode-inputValidation-infoBorder": "#007acc",
  "--vscode-dropdown-background": "#313131",
  "--vscode-dropdown-border": "#3c3c3c",
  "--vscode-dropdown-foreground": "#cccccc",
  "--vscode-menu-background": "#1f1f1f",
  "--vscode-menu-foreground": "#cccccc",
  "--vscode-menu-border": "#454545",
  "--vscode-badge-background": "#616161",
  "--vscode-badge-foreground": "#f8f8f8",
  "--vscode-progressBar-background": "#0078d4",
  "--vscode-scrollbarSlider-background": "rgba(121, 121, 121, 0.4)",
  "--vscode-scrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
  "--vscode-scrollbarSlider-activeBackground": "rgba(191, 191, 191, 0.4)",
  "--vscode-keybindingLabel-background": "rgba(128, 128, 128, 0.17)",
  "--vscode-keybindingLabel-foreground": "#cccccc",
  "--vscode-keybindingLabel-border": "rgba(51, 51, 51, 0.6)",
  "--vscode-charts-foreground": "#cccccc",
  "--vscode-charts-red": "#f14c4c",
  "--vscode-charts-blue": "#3794ff",
  "--vscode-charts-yellow": "#cca700",
  "--vscode-charts-orange": "#d18616",
  "--vscode-charts-green": "#89d185",
  "--vscode-charts-purple": "#b180d7",
  "--vscode-testing-iconPassed": "#73c991",
  "--vscode-testing-iconFailed": "#f14c4c",
  "--vscode-gitDecoration-addedResourceForeground": "#81b88b",
  "--vscode-gitDecoration-deletedResourceForeground": "#c74e39",
  "--vscode-diffEditor-insertedTextBackground": "rgba(156, 204, 44, 0.2)",
  "--vscode-diffEditor-removedTextBackground": "rgba(255, 0, 0, 0.2)",
  "--vscode-checkbox-background": "#313131",
  "--vscode-checkbox-border": "#3c3c3c",
  "--vscode-checkbox-foreground": "#cccccc",
};

const LIGHT_MODERN = {
  ...FONT,
  "--vscode-foreground": "#3b3b3b",
  "--vscode-descriptionForeground": "#616161",
  "--vscode-disabledForeground": "rgba(97, 97, 97, 0.5)",
  "--vscode-errorForeground": "#f85149",
  "--vscode-focusBorder": "#005fb8",
  "--vscode-contrastBorder": "",
  "--vscode-widget-border": "#e5e5e5",
  "--vscode-widget-shadow": "rgba(0, 0, 0, 0.16)",
  "--vscode-sideBar-background": "#f8f8f8",
  "--vscode-editor-background": "#ffffff",
  "--vscode-editor-foreground": "#3b3b3b",
  "--vscode-editor-selectionBackground": "#add6ff",
  "--vscode-editorLineNumber-foreground": "#6e7681",
  "--vscode-editorWidget-background": "#f8f8f8",
  "--vscode-editorWidget-border": "#c8c8c8",
  "--vscode-editorWarning-foreground": "#bf8803",
  "--vscode-editorGroupHeader-tabsBackground": "#f8f8f8",
  "--vscode-tab-activeBackground": "#ffffff",
  "--vscode-panel-border": "#e5e5e5",
  "--vscode-toolbar-hoverBackground": "rgba(184, 184, 184, 0.31)",
  "--vscode-list-hoverBackground": "#f2f2f2",
  "--vscode-list-activeSelectionBackground": "#e8e8e8",
  "--vscode-list-activeSelectionForeground": "#000000",
  "--vscode-textLink-foreground": "#005fb8",
  "--vscode-textLink-activeForeground": "#005fb8",
  "--vscode-textBlockQuote-background": "#f8f8f8",
  "--vscode-textBlockQuote-border": "#e5e5e5",
  "--vscode-textCodeBlock-background": "#f8f8f8",
  "--vscode-textPreformat-foreground": "#3b3b3b",
  "--vscode-button-background": "#005fb8",
  "--vscode-button-foreground": "#ffffff",
  "--vscode-button-hoverBackground": "#0258a8",
  "--vscode-button-border": "rgba(0, 0, 0, 0.1)",
  "--vscode-button-secondaryBackground": "#e5e5e5",
  "--vscode-button-secondaryForeground": "#3b3b3b",
  "--vscode-button-secondaryHoverBackground": "#cccccc",
  "--vscode-input-background": "#ffffff",
  "--vscode-input-border": "#cecece",
  "--vscode-input-foreground": "#3b3b3b",
  "--vscode-input-placeholderForeground": "#767676",
  "--vscode-inputValidation-errorBackground": "#f2dede",
  "--vscode-inputValidation-errorBorder": "#be1100",
  "--vscode-inputValidation-warningBackground": "#f6f5d2",
  "--vscode-inputValidation-warningBorder": "#b89500",
  "--vscode-inputValidation-infoBackground": "#d6ecf2",
  "--vscode-inputValidation-infoBorder": "#007acc",
  "--vscode-dropdown-background": "#ffffff",
  "--vscode-dropdown-border": "#cecece",
  "--vscode-dropdown-foreground": "#3b3b3b",
  "--vscode-menu-background": "#ffffff",
  "--vscode-menu-foreground": "#3b3b3b",
  "--vscode-menu-border": "#cecece",
  "--vscode-badge-background": "#cccccc",
  "--vscode-badge-foreground": "#3b3b3b",
  "--vscode-progressBar-background": "#005fb8",
  "--vscode-scrollbarSlider-background": "rgba(100, 100, 100, 0.4)",
  "--vscode-scrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
  "--vscode-scrollbarSlider-activeBackground": "rgba(0, 0, 0, 0.6)",
  "--vscode-keybindingLabel-background": "rgba(221, 221, 221, 0.4)",
  "--vscode-keybindingLabel-foreground": "#3b3b3b",
  "--vscode-keybindingLabel-border": "rgba(204, 204, 204, 0.4)",
  "--vscode-charts-foreground": "#3b3b3b",
  "--vscode-charts-red": "#e51400",
  "--vscode-charts-blue": "#1a85ff",
  "--vscode-charts-yellow": "#bf8803",
  "--vscode-charts-orange": "#d18616",
  "--vscode-charts-green": "#388a34",
  "--vscode-charts-purple": "#652d90",
  "--vscode-testing-iconPassed": "#388a34",
  "--vscode-testing-iconFailed": "#e51400",
  "--vscode-gitDecoration-addedResourceForeground": "#587c0c",
  "--vscode-gitDecoration-deletedResourceForeground": "#ad0707",
  "--vscode-diffEditor-insertedTextBackground": "rgba(156, 204, 44, 0.25)",
  "--vscode-diffEditor-removedTextBackground": "rgba(255, 0, 0, 0.2)",
  "--vscode-checkbox-background": "#f8f8f8",
  "--vscode-checkbox-border": "#cecece",
  "--vscode-checkbox-foreground": "#3b3b3b",
};

const HIGH_CONTRAST = {
  ...FONT,
  "--vscode-foreground": "#ffffff",
  "--vscode-descriptionForeground": "rgba(255, 255, 255, 0.7)",
  "--vscode-disabledForeground": "#a5a5a5",
  "--vscode-errorForeground": "#f48771",
  "--vscode-focusBorder": "#f38518",
  "--vscode-contrastBorder": "#6fc3df",
  "--vscode-contrastActiveBorder": "#f38518",
  "--vscode-widget-border": "#6fc3df",
  "--vscode-widget-shadow": "",
  "--vscode-sideBar-background": "#000000",
  "--vscode-editor-background": "#000000",
  "--vscode-editor-foreground": "#ffffff",
  "--vscode-editor-selectionBackground": "#ffffff",
  "--vscode-editorLineNumber-foreground": "#ffffff",
  "--vscode-editorWidget-background": "#0c141f",
  "--vscode-editorWidget-border": "#6fc3df",
  "--vscode-editorWarning-foreground": "#ff0000",
  "--vscode-editorGroupHeader-tabsBackground": "#000000",
  "--vscode-tab-activeBackground": "#000000",
  "--vscode-panel-border": "#6fc3df",
  "--vscode-toolbar-hoverBackground": "",
  "--vscode-list-hoverBackground": "",
  "--vscode-list-activeSelectionBackground": "",
  "--vscode-list-activeSelectionForeground": "#ffffff",
  "--vscode-textLink-foreground": "#21a6ff",
  "--vscode-textLink-activeForeground": "#21a6ff",
  "--vscode-textBlockQuote-background": "#000000",
  "--vscode-textBlockQuote-border": "#ffffff",
  "--vscode-textCodeBlock-background": "#000000",
  "--vscode-textPreformat-foreground": "#ffd700",
  "--vscode-button-background": "#000000",
  "--vscode-button-foreground": "#ffffff",
  "--vscode-button-hoverBackground": "",
  "--vscode-button-border": "#6fc3df",
  "--vscode-button-secondaryBackground": "",
  "--vscode-button-secondaryForeground": "#ffffff",
  "--vscode-button-secondaryHoverBackground": "",
  "--vscode-input-background": "#000000",
  "--vscode-input-border": "#6fc3df",
  "--vscode-input-foreground": "#ffffff",
  "--vscode-input-placeholderForeground": "rgba(255, 255, 255, 0.7)",
  "--vscode-inputValidation-errorBackground": "#000000",
  "--vscode-inputValidation-errorBorder": "#6fc3df",
  "--vscode-inputValidation-warningBackground": "#000000",
  "--vscode-inputValidation-warningBorder": "#6fc3df",
  "--vscode-inputValidation-infoBackground": "#000000",
  "--vscode-inputValidation-infoBorder": "#6fc3df",
  "--vscode-dropdown-background": "#000000",
  "--vscode-dropdown-border": "#6fc3df",
  "--vscode-dropdown-foreground": "#ffffff",
  "--vscode-menu-background": "#000000",
  "--vscode-menu-foreground": "#ffffff",
  "--vscode-menu-border": "#6fc3df",
  "--vscode-badge-background": "#000000",
  "--vscode-badge-foreground": "#ffffff",
  "--vscode-progressBar-background": "#6fc3df",
  "--vscode-scrollbarSlider-background": "rgba(111, 195, 223, 0.6)",
  "--vscode-scrollbarSlider-hoverBackground": "rgba(111, 195, 223, 0.8)",
  "--vscode-scrollbarSlider-activeBackground": "#6fc3df",
  "--vscode-keybindingLabel-background": "",
  "--vscode-keybindingLabel-foreground": "#ffffff",
  "--vscode-keybindingLabel-border": "#6fc3df",
  "--vscode-charts-foreground": "#ffffff",
  "--vscode-charts-red": "#f14c4c",
  "--vscode-charts-blue": "#3794ff",
  "--vscode-charts-yellow": "#cca700",
  "--vscode-charts-orange": "#d18616",
  "--vscode-charts-green": "#89d185",
  "--vscode-charts-purple": "#b180d7",
  "--vscode-testing-iconPassed": "#73c991",
  "--vscode-testing-iconFailed": "#f14c4c",
  "--vscode-gitDecoration-addedResourceForeground": "#a1e3ad",
  "--vscode-gitDecoration-deletedResourceForeground": "#c74e39",
  "--vscode-diffEditor-insertedTextBackground": "",
  "--vscode-diffEditor-removedTextBackground": "",
  "--vscode-checkbox-background": "#000000",
  "--vscode-checkbox-border": "#6fc3df",
  "--vscode-checkbox-foreground": "#ffffff",
};

export const THEMES = {
  dark: { kind: "vscode-dark", vars: DARK_MODERN },
  light: { kind: "vscode-light", vars: LIGHT_MODERN },
  hc: { kind: "vscode-high-contrast", vars: HIGH_CONTRAST },
};

/** `:root { … }` for one theme. Empty values are left out, the way VS Code
 *  leaves out a colour a theme does not define. */
export function themeCss(name) {
  const theme = THEMES[name];
  if (!theme) throw new Error(`unknown theme ${name}`);
  const lines = Object.entries(theme.vars)
    .filter(([, value]) => value !== "")
    .map(([key, value]) => `  ${key}: ${value};`);
  return `:root {\n${lines.join("\n")}\n}`;
}
