import esbuild from "esbuild";
import path from "node:path";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const isWatch = process.argv.includes("--watch");

/** @type {esbuild.BuildOptions} */
const buildOptions = {
  entryPoints: {
    extension: path.join(root, "src/extension.ts"),
    "agy-acp-adapter": path.join(root, "src/agy-acp-adapter.ts"),
  },
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node20",
  sourcemap: true,
  outdir: path.join(root, "out"),
  external: [
    "vscode",
    "@agentclientprotocol/codex-acp",
    "@agentclientprotocol/claude-agent-acp",
    "@anthropic-ai/claude-agent-sdk",
    "@muse-code/sdk",
  ],
  logLevel: "info",
};

/** Shared options also drive the read-only freshness check. */
const sharedOptions = {
  absWorkingDir: root,
  entryPoints: ["src/webview-shared.ts"],
  bundle: true, platform: "browser", format: "iife", target: "es2022",
  globalName: "GrokWebviewShared", minifyIdentifiers: true,
  outfile: path.join(root, "media/generated/webview-shared.js"),
  banner: { js: "// Generated by scripts/build.mjs from src/webview-shared.ts. Do not edit." },
  footer: { js: 'if (typeof module !== "undefined" && module.exports) module.exports = GrokWebviewShared; else globalThis.GrokWebviewShared = GrokWebviewShared;' },
  metafile: true,
};

// Browser builds cannot externalize host dependencies. Audit every bundled input.
function assertBrowserInputs(result) {
  const allowed = new Set(["src/webview-shared.ts", "src/protocol.ts", "src/slash-filter.ts",
    "src/shared/context-chip.ts", "src/shared/queued-send.ts", "src/shared/subagent-chip.ts", "src/shared/line-diff.ts"]);
  for (const input of Object.keys(result.metafile.inputs)) {
    if (!allowed.has(input)) throw new Error("Unexpected browser dependency: " + input);
  }
  for (const output of Object.values(result.metafile.outputs)) {
    if (output.imports.length) throw new Error("Browser bundle has external imports");
  }
}

if (process.argv.includes("--check-shared")) {
  const result = await esbuild.build({ ...sharedOptions, write: false });
  assertBrowserInputs(result);
  const expected = readFileSync(sharedOptions.outfile);
  if (!expected.equals(result.outputFiles[0].contents)) {
    throw new Error("Stale webview-shared.js: run npm run compile and commit the generated file");
  }
} else if (process.argv.includes("--shared-only")) {
  const result = await esbuild.build(sharedOptions);
  assertBrowserInputs(result);
} else if (isWatch) {
  const ctx = await esbuild.context(buildOptions);
  const sharedCtx = await esbuild.context(sharedOptions);
  await ctx.watch();
  await sharedCtx.watch();
  console.log("Watching for changes...");
} else {
  await esbuild.build(buildOptions);
  const sharedResult = await esbuild.build(sharedOptions);
  assertBrowserInputs(sharedResult);
}
